### ISSUE TITLE
Limpar Projeto

### ISSUE THREAD

**Issue by paulorsouza** [fabiokiatkowski/orion-ui#2]
**Hoje**: Esse projeto foi criado para experiencia do sistema de controle Orion, porem a segunda fase do projeto esta em um repositorio privado.

**Ideia**: Transformar esse projeto em um projeto de testes para novas funcionalidades não ligadas a regra de negocio.

_Apagar todas regras de negocio do projeto, manter apenas funcionalidades não ligadas a regra de negocio nesse projeto_

**Comment by fabiokiatkowski** [comment]
Projeto limpo?
